CCINCS	= $(shell $(CC) -print-search-dirs | grep install | cut -f2 -d' ')/include
INCDIRS	= Source/include ../../libs/slibc/include $(CCINCS)
INCLUDE	= $(foreach f, $(INCDIRS), -I$(f) )

LIBNAME = freertos
include $(MENGINE)/makelib.mk
